def get_dummy_bounding_boxes():
    return [
        {
            "name": "Segment 1",
            "bbox": [40.0, 10.0, 102.0, 105.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 2",
            "bbox": [447.0, 273.0, 17.0, 168.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 3",
            "bbox": [307.0, 273.0, 17.0, 168.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 4",
            "bbox": [401.0, 273.0, 16.0, 168.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 5",
            "bbox": [262.0, 273.0, 17.0, 168.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 6",
            "bbox": [353.0, 273.0, 17.0, 168.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 7",
            "bbox": [219.0, 273.0, 16.0, 168.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 8",
            "bbox": [270.0, 57.0, 22.0, 22.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 9",
            "bbox": [154.0, 236.0, 110.0, 17.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 10",
            "bbox": [492.0, 196.0, 61.0, 29.0],
            "hasText": True,
            "isObstacle": True,
        },
        {
            "name": "Segment 11",
            "bbox": [252.0, 57.0, 19.0, 16.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 12",
            "bbox": [339.0, 136.0, 43.0, 33.0],
            "hasText": False,
            "isObstacle": False,
        },
        {
            "name": "Segment 13",
            "bbox": [580.0, 57.0, 19.0, 16.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 14",
            "bbox": [458.0, 57.0, 19.0, 17.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 15",
            "bbox": [467.0, 137.0, 51.0, 32.0],
            "hasText": True,
            "isObstacle": True,
        },
        {
            "name": "Segment 16",
            "bbox": [159.0, 51.0, 23.0, 22.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 17",
            "bbox": [331.0, 196.0, 31.0, 29.0],
            "hasText": True,
            "isObstacle": True,
        },
        {
            "name": "Segment 18",
            "bbox": [294.0, 236.0, 261.0, 8.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 19",
            "bbox": [149.0, 308.0, 8.0, 9.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 20",
            "bbox": [172.0, 212.0, 9.0, 9.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 21",
            "bbox": [237.0, 211.0, 10.0, 10.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 22",
            "bbox": [193.0, 461.0, 34.0, 20.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 23",
            "bbox": [237.0, 462.0, 14.0, 19.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 24",
            "bbox": [149.0, 273.0, 8.0, 10.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 25",
            "bbox": [542.0, 358.0, 10.0, 20.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 26",
            "bbox": [587.0, 262.0, 63.0, 245.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 27",
            "bbox": [501.0, 393.0, 53.0, 8.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 28",
            "bbox": [384.0, 137.0, 81.0, 32.0],
            "hasText": True,
            "isObstacle": True,
        },
        {
            "name": "Segment 29",
            "bbox": [472.0, 462.0, 14.0, 19.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 30",
            "bbox": [93.0, 33.0, 31.0, 59.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 31",
            "bbox": [301.0, 462.0, 13.0, 19.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 32",
            "bbox": [57.0, 32.0, 35.0, 62.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 33",
            "bbox": [542.0, 272.0, 10.0, 19.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 34",
            "bbox": [375.0, 57.0, 19.0, 16.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 35",
            "bbox": [489.0, 51.0, 23.0, 22.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 36",
            "bbox": [149.0, 290.0, 8.0, 10.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 37",
            "bbox": [145.0, 359.0, 8.0, 30.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 38",
            "bbox": [578.0, 235.0, 9.0, 144.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 39",
            "bbox": [86.0, 136.0, 247.0, 34.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 40",
            "bbox": [511.0, 471.0, 10.0, 17.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 41",
            "bbox": [395.0, 57.0, 16.0, 16.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 42",
            "bbox": [258.0, 462.0, 14.0, 19.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 43",
            "bbox": [322.0, 462.0, 14.0, 19.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 44",
            "bbox": [332.0, 196.0, 159.0, 39.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 45",
            "bbox": [280.0, 462.0, 13.0, 19.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 46",
            "bbox": [344.0, 462.0, 13.0, 19.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 47",
            "bbox": [317.0, 57.0, 20.0, 16.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 48",
            "bbox": [520.0, 136.0, 130.0, 33.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 49",
            "bbox": [363.0, 196.0, 187.0, 39.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 50",
            "bbox": [587.0, 236.0, 63.0, 49.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 51",
            "bbox": [532.0, 52.0, 13.0, 21.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 52",
            "bbox": [561.0, 307.0, 6.0, 34.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 53",
            "bbox": [196.0, 52.0, 24.0, 21.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 54",
            "bbox": [578.0, 235.0, 8.0, 199.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 55",
            "bbox": [313.0, 489.0, 358.0, 54.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 56",
            "bbox": [410.0, 178.0, 78.0, 9.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 57",
            "bbox": [600.0, 203.0, 50.0, 31.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 58",
            "bbox": [116.0, 475.0, 33.0, 19.0],
            "hasText": True,
            "isObstacle": True,
        },
        {
            "name": "Segment 59",
            "bbox": [181.0, 258.0, 45.0, 7.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 60",
            "bbox": [424.0, 52.0, 13.0, 21.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 61",
            "bbox": [125.0, 191.0, 175.0, 36.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 62",
            "bbox": [510.0, 58.0, 20.0, 15.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 63",
            "bbox": [437.0, 52.0, 19.0, 21.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 64",
            "bbox": [120.0, 282.0, 5.0, 25.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 65",
            "bbox": [542.0, 316.0, 10.0, 20.0],
            "hasText": False,
            "isObstacle": True,
        },
        {
            "name": "Segment 66",
            "bbox": [340.0, 572.0, 43.0, 12.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 67",
            "bbox": [584.0, 179.0, 34.0, 5.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 68",
            "bbox": [119.0, 282.0, 7.0, 26.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 69",
            "bbox": [552.0, 470.0, 24.0, 26.0],
            "hasText": True,
            "isObstacle": True,
        },
        {
            "name": "Segment 70",
            "bbox": [326.0, 487.0, 49.0, 6.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 71",
            "bbox": [231.0, 58.0, 20.0, 15.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 72",
            "bbox": [617.0, 261.0, 33.0, 23.0],
            "hasText": True,
            "isObstacle": False,
        },
        {
            "name": "Segment 73",
            "bbox": [152.0, 502.0, 23.0, 5.0],
            "hasText": True,
            "isObstacle": True,
        },
        {
            "name": "Segment 74",
            "bbox": [307.0, 57.0, 10.0, 16.0],
            "hasText": False,
            "isObstacle": False,
        },
        {
            "name": "Segment 75",
            "bbox": [584.0, 178.0, 34.0, 15.0],
            "hasText": True,
            "isObstacle": False,
        },
    ]
